/* eslint-disable @nx/enforce-module-boundaries */
import { effect, Injectable, signal } from "@angular/core";
import { BehaviorSubject, Observable } from "rxjs";
import { HttpClient } from "@angular/common/http";
import { enviroment } from "apps/gfw-portal/env/dev.env";
type PermissionSchema = {
  [module: string]: {
    __FULL__?: boolean;
    [feature: string]: {
      [action: string]: boolean;
    } | any;
  };
};

type PermissionAction = 'VIEW' | 'ADD' | 'EDIT' | 'FULL' | 'DELETE';

@Injectable({
  providedIn: 'root'
})
export class PermissionSystemService {

  // 1️⃣ RAW permissions from backend
 private PERMSSION: BehaviorSubject<string[]> = new BehaviorSubject<string[]>([]);



 setPermissions(permissions: string[]) {
  this.PERMSSION.next(permissions);
  const schema = this.handlePermissionSchema(permissions);
  this.permissionSchema.set(schema);
}


refreshUserPermissions():Observable<any>{
  return this.http.get(enviroment.API_URL + `Permissions/TechnicalName`)
}


  // 2️⃣ System definition (frontend knowledge)
  private MODULE_DEFINITION: Record<string, string[]> = {
    // RISKS: ['RISK', 'ASSESSMENT', 'TREATMENT', "TREATMENT_ATTACHMENT" , "TREATMENT_COMMENT",'TREATMENT_RESPONSEACTION','RISK_QUESTIONNAIRE', "RISK_COMMENT" , "RISK_ATTACHMENT" , "ASSESSMENT_COMMENT" , "ASSESSMENT_ATTACHMENT" , "RISKASSESSMENTCONTROLEVALUATION","RISK_LINKEDMODULE" , "RISK_ROORCAUSE" , 'METHODOLOGY' , 'METHODOLOGY_COMMENT', 'METHODOLOGY_ATTACHMENT','METHODOLOGYFACTORS', 'METHODOLOGYFACTORS_COMMENT' , 'METHODOLOGYFACTORS_ATTACHMENT', 'METHODOLOGYFACTORLEVELS' , 'METHODOLOGYFACTORLEVELS_COMMENT' , 'METHODOLOGYFACTORLEVELS_ATTACHMENT' ,'METHODOLOGYLIKEHOOD','METHODOLOGYIMPACT', 'METHODOLOGYLEVELS','RISKASSESSMENTFORMULA', 'RISKASSESSMENTFORMULAFACTORS','METHODOLOGYAPPETITE','METHODOLOGYTOLERANCE','METHODOLOGYEFFECTIVEFORMULA','METHODOLOGYEFFECTIVEFORMULA_COMMENT' , 'METHODOLOGYEFFECTIVEFORMULA_ATTACHMENT' , 'RISKS_INDICATORS' , 'RISKS_INDICATORMEASURMENT' , 'RISKS_INDICATORCOMMENT' , 'RISKS_INDICATORATTACHMENT' ],
    // GOVERNANCE:['CONTROLS' , 'CONTROL_ATTACHMENT','CONTROL_COMMENT','CONTROLASSESSMENT' , 'CONTROLASSESSMENT_COMMENT' , 'CONTROLASSESSMENT_ATTACHMENT' , 'CONTROL_LINKEDMODULE' ,   'CONTROLREQUIRMENT' , 'CONTROLREQUIRMENT_COMMENT' , 'CONTROLREQUIRMENT_ATTACHMENT' , 'COVDOCUMENT' , 'GOVDOCUMENT_ATTACHMENT' , 'COVDOCUMENT_COMMENT','VERSION','VERSION_COMMENT','VERSION_ATTACHMENT', 'VERSIONCONTENT' , 'REVIEWS', 'REVIEWSCOMMENT' ,'REVIEWS_COMMENT' , 'REVIEWS_ATTACHMENT', 'APPROVAL','APPROVAL_COMMENT' , 'APPROVAL_ATTACHMENT' , 'VERSION_REVIEWCOMMENTS' ],
    // GOVERNANCE:['GOVDOCUMENTSTACKHOLDERS' , 'GOVDOCUMENTSTACKHOLDERSAPPROVERS' , 'GOVDOCUMENTSTACKHOLDERSREVIEWERS']
    // COMPLIANCE:['COMPLIANCE_DOCUMENTS','COMPLIANCEDOCUMENTSCONTENT','COMPLIANCEASSESSMENTS','COMPLIANCEASSESSMENTSCONTROL','COMPLIANCEASSESSMENTSCONTROLEVIDENCES','COMPLIANCEASSESSMENTSCONTROL_FINDINGS','COMPLIANCEASSESSMENTSCONTROL_ASSESSMENT','COMPLIANCEASSESSMENTSCONTROL_CORRECTIVEACTION','COMPLIANCEASSESSMENTSCONTROLREQUIREMENTACTION','COMPLIANCEASSESSMENTSCONTROLPROCEDURE','COMPLIANCEASSESSMENTSCONTROL_EVIDENCETASK','COMPLIANCEASSESSMENTS_EVIDENCETASK','COMPLIANCEASSESSMENTS_FINDINGS','COMPLIANCEASSESSMENTS_CORRECTIVEACTION','COMPLIANCEAUTHORITIES','COMPLIANCEAUTHORITIESCOMPETENT','COMPLIANCEINDICATORS','COMPLIANCEINDICATORSMEASUREMENTS','COMPLIANCEEVIDENCE','COMPLIANCEEVIDENCEVERSION','COMPLIANCEEVIDENCECONTROL']
    // COMPLIANCE:["COMPLIANCEDOCUMENT" , "COMPLIANCEDOCUMENT_ATTACHMENTS" , "COMPLIANCEDOCUMENT_COMMENTS" , "COMPLIANCEDOCUMENTCONTENT",'COMPLIANCEDOCUMENTCONTENT_REQUIREMENTCONTROL','COMPLIANCEDOCUMENTCONTENT_REQUIREMENTCONTROL_COMMENTS','COMPLIANCEDOCUMENTCONTENT_REQUIREMENTCONTROL_ATTACHMENTS'
    //   //
    //    , "ASSESSMENT" , "ASSESSMENT_COMMENTS" ,"ASSESSMENT_ATTACHMENTS",'ASSSESSMENT_CONTROLS','ASSESSMENT_EVIDENCETASK','ASSESSMENT_EVIDENCETASK_COMMENTS','ASSESSMENT_EVIDENCETASK_ATTACHMENTS','ASSESSMENT_FINDINGS','ASSESSMENT_FINDINGS_COMMENTS','ASSESSMENT_FINDINGS_ATTACHMENTS','ASSESSMENT_CORREECTIVEACTION'
    //   //
    //   ,'COMPETENTAUTHORITIES'
    //   //
    //   ,"ONGOINGASSESSMENT" , "ONGOINGASSESSMENT_COMMENTS" ,"ONGOINGASSESSMENT_ATTACHMENTS",'ONGOINGASSSESSMENT_CONTROLS',
    //   'ONGOINGASSSESSMENT_CONTROLS_COMMENTS','ONGOINGASSSESSMENT_CONTROLSEVIDENCES','ONGOINGASSSESSMENT_CONTROLS_EVIDENCETASK','ONGOINGASSSESSMENT_CONTROLS_EVIDENCETASK_ATTACHMENTS','ONGOINGASSSESSMENT_CONTROLS_EVIDENCETASK_COMMENTS','ONGOINGASSSESSMENT_CONTROLS_FINDINGS','ONGOINGASSSESSMENT_CONTROLS_FINDINGS_COMMENTS','ONGOINGASSSESSMENT_CONTROLS_FINDINGS_ATTACHMENTS','ONGOINGASSSESSMENT_CONTROLSASSESSMENT','ONGOINGASSSESSMENT_CONTROLS_CORRECTIVEACTION',
    //   'ONGOINGASSSESSMENT_CONTROLS_CORRECTIVEACTION_COMMENTS','ONGOINGASSSESSMENT_CONTROLS_CORRECTIVEACTION_ATTACHMENTS',
    //   'ONGOINGASSSESSMENT_CONTROLS_REQUIREMENTCONTROL','ONGOINGASSSESSMENT_CONTROLSPROCEDURE',
    //   'ONGOINGASSESSMENT_EVIDENCETASK','ONGOINGASSESSMENT_EVIDENCETASK_COMMENTS','ONGOINGASSESSMENT_EVIDENCETASK_ATTACHMENTS','ONGOINGASSESSMENT_FINDINGS','ONGOINGASSESSMENT_FINDINGS_COMMENTS','ONGOINGASSESSMENT_FINDINGS_ATTACHMENTS','ONGOINGASSESSMENT_CORREECTIVEACTION',
    //     //
    //   'KEYCOMPLIANCEINDICATORS','KEYCOMPLIANCEINDICATORS_COMMENTS','KEYCOMPLIANCEINDICATORS_ATTACHMENTS','KEYCOMPLIANCEINDICATORSMEASURMENTLIST',
    //   //
    //   'EVIDENCECOMPLIANCE','EVIDENCECOMPLIANCE_COMMENTS','EVIDENCECOMPLIANCE_ATTACHMENTS','EVIDENCECOMPLIANCEVERSION','EVIDENCECOMPLIANCECONTROL']

    // LIBRARY:['STANDARDDOCUMENTS','STANDARDDOCUMENTS_CONTROLS','STANDARDDOCUMENTS_CONTROLS_REQUIREMENTS','STANDARDDOCUMENTS_CONTROLS_REQUIREMENTS_ATTACHMENTS','STANDARDDOCUMENTS_CONTROLS_REQUIREMENTS_COMMENTS',
    // 'SYSTEMDOCUMENTS'
    // ]

    // THIRDPARTIES:[
    //   'THIRDPARTY','THIRDPARTYCONTACT','THIRDPARTYCONTRACT','THIRDPARTYDUEDILIGENCE','THIRDPARTYASSESSMENT','THIRDPARTYACTIVITY','THIRDPARTYEXCEPTIONS','THIRDPARTYQUESTIONNAIRE','THIRDPARTYCONTRACTSLA',
    //   'THIRDPARTYDUEDILIGENCE_ATTACHMENTS','THIRDPARTYDUEDILIGENCE_COMMENTS','THIRDPARTYASSESSMENT_ATTACHMENTS','THIRDPARTYASSESSMENT_COMMENTS','THIRDPARTYACTIVITY_ATTACHMENTS','THIRDPARTYACTIVITY_COMMENTS','THIRDPARTYEXCEPTIONS_ATTACHMENTS','THIRDPARTYEXCEPTIONS_COMMENTS','THIRDPARTYQUESTIONNAIREANSWERS','THIRDPARTYQUESTIONNAIRESECTIONS','THIRDPARTYQUESTIONNAIRESECTIONQUESTIONS','THIRDPARTYINDICATORS','THIRDPARTYINDICATORS_ATTACHMENTS','THIRDPARTYINDICATORS_COMMENTS','THIRDPARTYINDICATORSMEASURMENTS'
    // ]

    // INDICATORS:[
    //   'INDICATORS','INDICATORSMEASURMENTS','INDICATORS_COMMENTS','INDICATORS_ATTACHMENTS'
    // ]

    // RISKS:[
    //   'METHODOLOGYCONTROLEFFECTIVENESSLEVELS','METHODOLOGYCONTROLASSESSMENTLEVELS'
    // ]

    // ESCLATIONS:['ESCLATION','ESCLATIONLEVELS','ESCLATIONCRITERIA','ESCLATIONTARGET','ESCLATIONNOTIFICATION']
      //  QUESTIONNAIRES:[ 'QUESTIONS','QUESTIONSQUESTIONNAIREANSWER','QUESTIONS_ATTACHMENTS','QUESTIONS_COMMENTS','INSTANCE','INSTANCEANSWERS','INSTANCESECTIONS','INSTANCESECTIONSQUESTIONS','INSTANCESECTIONSQUESTIONS_COMMENTS','INSTANCESECTIONSQUESTIONS_ATTACHMENTS','TEMPLATES','TEMPLATESSECTIONS','TEMPLATESSECTIONSQUESTIONS','MYQUESTIONNAIRES' ]
      INDICATORS:['INDICATORTHRESHOLD','INDICATORFORMULAS','INDICATORINPUTS']

  };

  private ACTIONS: readonly PermissionAction[] = ['VIEW', 'ADD', 'EDIT', 'DELETE','FULL'];

  permissionSchema = signal<PermissionSchema>({});
  private SETTING_USER = signal<any[]>([]);
  getSETTING_USER(){
    const sett = JSON.parse(`${localStorage.getItem('userData')}`)?.settings;
    this.SETTING_USER.set(sett)
    return this.SETTING_USER()
  }
  constructor(private http: HttpClient) {
    this.SETTING_USER.set(JSON.parse(`${localStorage.getItem('userData')}`)?.settings);

    const expanded = this.generateAllPermissionsFromDefinition(
      this.MODULE_DEFINITION,
      this.ACTIONS
    );
    console.log(expanded,'expanded');



    // this.PERMSSION.subscribe(permissions => {
    //   const schema = this.handlePermissionSchema(permissions);
    //   this.permissionSchema.set(schema);
    //   console.log("permissionSchema" , this.permissionSchema());

    // });

  }

  // =====================================================
  // 3️⃣ Expand MODULE.FULL → all sub-modules & actions
  // =====================================================
private generateAllPermissionsFromDefinition(
  moduleMap: Record<string, string[]>,
  actions: readonly PermissionAction[]
): string[] {
  const result = new Set<string>();

  Object.entries(moduleMap).forEach(([module, subs]) => {
    // MODULE FULL
    result.add(`${module}.FULL`);

    subs.forEach(sub => {
      actions.forEach(action => {
        result.add(`${module}.${sub}.${action}.ALL`);
      });
    });
  });

  return Array.from(result);
}

  // =====================================================
  // 4️⃣ Build permission schema
  // =====================================================
  handlePermissionSchema(permissions: string[]): PermissionSchema {
    const schema: PermissionSchema = {};

    permissions.forEach(permission => {
      const parts = permission.split('.');

      // MODULE.FULL
      if (parts.length === 2 && parts[1] === 'FULL') {
        const module = parts[0];
        schema[module] ??= {};
        schema[module].__FULL__ = true;
        return;
      }

      // MODULE.FEATURE.ACTION
      if (parts.length === 3) {
        const [module, feature, action] = parts;

        schema[module] ??= {};
        schema[module][feature] ??= {};
        schema[module][feature][action] = true;
      }
    });

    return schema;
  }

  // =====================================================
  // 5️⃣ Permission check API (unchanged & clean)
  // =====================================================
can(module: string, feature?: string, action?: string): boolean {
  const schema = this.permissionSchema();
  const mod = schema[module];
  if (!mod) return false;

  // 1️⃣ MODULE.FULL
  if (mod.__FULL__) return true;

  // MODULE LEVEL ONLY
  if (!feature) return true;

  const feat = mod[feature];
  if (!feat) return false;

  if (feat['FULL']) return true;

  // FEATURE LEVEL ONLY
  if (!action) return true;

  // 3️⃣ ACTION LEVEL
  return !!feat[action];
}


showWF():boolean{
  const S004 = this.getSETTING_USER().find(s => s.code === 'S004')

  if(!S004)return false
  console.log('S004',S004);

  return S004.value === 'true'

}


}
